/**
 * |-------------------------------------------------------------|
 *  Person.cpp
 *  David Schurer, Philip Vu, Prajeet Pounraj
 *  CSS 343 - Prof. Rahman
 *  1st June, 2023
 * |-------------------------------------------------------------|
 * Description:
 * The Person class represents a person in the movie rental shop's automated
 * inventory tracking system. It inherits from the HashObject class and provides 
 * functionality to store the first name and last name of a person. Derived classes
 * can be created from this base class to represent specific types of persons, such 
 * as customers or directors.
 * |-------------------------------------------------------------|
 * Assume:
 * The program assumes that the HashObject class have been properly implemented.
*/
#include "../headers/Person.h"

/** |----------------------------------------Constructor-------------------------------------------------|
 *   Description: The Person class constructor is responsible for initializing a Person object, which
 *   represents a person in the movie rental shop. It initializes the first and last name of the 
 *   person.
 *  |----------------------------------------------------------------------------------------------------|
*/
Person::Person(string firstName, string lastName) : firstName(firstName), lastName(lastName)
{
}

/** |----------------------------------------getFirstName------------------------------------------------|
 *   Description: The getFirstName method for the Person class is a getter method that is responsible for 
 *   retrieving the first name of the person in the movie rental shop. It returns their first name
 *   as a string.
 *  |----------------------------------------------------------------------------------------------------|
*/
string Person::getFirstName() const
{
    return this->firstName;
}

/** |----------------------------------------getLastName-------------------------------------------------|
 *   Description: The getLastName method for the Person class is a getter method that is responsible for
 *   retrieving the last name of a person in the movie rental shop. It returns their last name
 *   as a string.
 *  |----------------------------------------------------------------------------------------------------|
*/
string Person::getLastName() const
{
    return this->lastName;
}

/** |----------------------------------------getFullName-------------------------------------------------|
 *   Description: The getFullName method for the Person class is a getter method that is responsible for
 *   retrieving the full name of the person in the movie rental shop. It concatenates the first name
 *   and the last name of the person and then returns their full name as a string.
 *  |----------------------------------------------------------------------------------------------------|
*/
string Person::getFullName() const
{
    return this->firstName + " " + this->lastName;
}

/** |-----------------------------------------hashCode---------------------------------------------------|
 *   Description: The hashCode method for the Person class is responsible for generating a unique
 *   hash code for each person in the movie rental shop. Each person's hash code is generated by
 *   concatenating their first name and their last name.
 *  |----------------------------------------------------------------------------------------------------|
*/
string Person::hashCode() const
{
    return this->firstName + this->lastName;
}
